version: 0.2

env:
  parameter-store:
    SPRING_DATASOURCE_URL: "SPRING_DATASOURCE_URL"
    SPRING_DATASOURCE_USERNAME: "SPRING_DATASOURCE_USERNAME"
    SPRING_DATASOURCE_PASSWORD: "SPRING_DATASOURCE_PASSWORD"

phases:
  pre_build:
    commands:
      - echo start pre build.

      # ログインユーザーの確認
      - id
      # OS情報の確認
      - cat /etc/system-release
      - cat /etc/os-release
      # 各種パッケージの最新化
      - yum update -y
      # タイムゾーンの変更
      - date
      - cp /usr/share/zoneinfo/Japan /etc/localtime
      - date
      # Javaのインストール
      - yum install -y java-17-amazon-corretto
      - java -version
      - /usr/sbin/alternatives --set java /usr/lib/jvm/java-17-amazon-corretto.aarch64/bin/java
      - java -version
      - /usr/sbin/alternatives --display java
      # JAVA_HOME環境変数の設定
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto.aarch64
      # Mavenのインストール
      - yum install -y maven
      - mvn -version

      - echo finish pre build.

  build:
    commands:
      - echo start build.

      # Spring Bootプロジェクトのビルド（jarの作成）
      - mvn package
      - ls -l target

      - echo finish build.

  post_build:
    commands:
      - echo start post build.

      # S3にアップロードするファイルを所定のディレクトリにコピー
      - mkdir artifacts
      - cp target/pcassem-0.0.1-SNAPSHOT.jar artifacts
      - cp appspec.yml artifacts
      - cp update.sh artifacts

      - echo finish post build.

artifacts:
  # S3にアップロードするファイルを指定
  files:
    - pcassem-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - update.sh
  # ベースディレクトリ
  base-directory: artifacts